const tires = [
    {
        id: 1,
        src: require("../assets/tire_1.png"),
        alt: "Image 1",
        name: "205/55R16 PIRELLI CINTURATO P7 91VPIRELLI CINTURATO P7 91V", 
        rating: "3",
        comment: "3",
        typeOfSeason: {
            winter: "1",
            studded: "1",
            mud: "1",
        },
        price: "6750",
        promo: "6750",
        quantity: "4",
    },
    {
        id: 2,
        src: require("../assets/tire_2.png"),
        alt: "Image 2 ",
        name: "205/55R16 PIRELLI CINTURATO P7 91VPIRELLI CINTURATO P7 91V", 
        rating: "2",
        comment: "7",
        typeOfSeason: {
            winter: "0",
            studded: "1",
            mud: "0",
        },
        price: "6750",
        promo: "6750",
        quantity: "4",
    },
    {
        id: 3,
        src: require("../assets/tire_3.png"),
        alt: "Image 3",
        name: "205/55R16 PIRELLI CINTURATO P7 91VPIRELLI CINTURATO P7 91V", 
        rating: "4",
        comment: "10",
        typeOfSeason: {
            winter: "0",
            studded: "0",
            mud: "1",
        },
        price: "6750",
        promo: "6750",
        quantity: "4",
    },
    {
        id: 4,
        src: require("../assets/tire_4.png"),
        alt: "Image 3",
        name: "205/55R16 PIRELLI CINTURATO P7 91VPIRELLI CINTURATO P7 91V", 
        rating: "5",
        comment: "5",
        typeOfSeason: {
            winter: "1",
            studded: "1",
            mud: "0",
        },
        price: "6750",
        promo: "6750",
        quantity: "4",
    },
    {
        id: 5,
        src: require("../assets/tire_5.png"),
        alt: "Image 3",
        name: "205/55R16 PIRELLI CINTURATO P7 91VPIRELLI CINTURATO P7 91V", 
        rating: "4",
        comment: "6",
        typeOfSeason: {
            winter: "1",
            studded: "1",
            mud: "1",
        },
        price: "6750",
        promo: "6750",
        quantity: "4",
    },
];
export default tires;